
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const NAME_CHANGED = 'NAME_CHANGED';
export const PRICE_CHANGED = 'PRICE_CHANGED';
export const IMAGE_URL_CHANGED = 'IMAGE_URL_CHANGED';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CREATED = 'CREATED';
